name: "Support Requests"

on:
    issues:
        types: [labeled]

permissions:
    issues: write

jobs:
    support:
        name: "Close support requests"
        runs-on: ubuntu-latest
        steps:
            - name: "Run the support-requests action"
              uses: dessant/support-requests@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  support-label: "support"
                  issue-comment: >
                      :wave: @{issue-author}, we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use GitHub Discussions to get help with the project.


                  close-issue: true
                  lock-issue: false
                  issue-lock-reason: "off-topic"
